# Generated by Django 3.0.3 on 2020-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200304_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=100, verbose_name='Ismi: '),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='Familyasi: '),
        ),
    ]
