# Generated by Django 3.0.3 on 2020-03-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200305_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.IntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Graduate')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('BT', 'Budjet'), ('KT', 'Kantrakt'), (' ', 'Boshqa')], default=' ', max_length=2, verbose_name="Ta'lim turi"),
        ),
    ]
