# Generated by Django 3.0.3 on 2020-03-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200305_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('BT', 'Budjet'), ('KT', 'Kantrakt')], default='BT', max_length=2, verbose_name="Ta'lim turi"),
        ),
    ]
