# Generated by Django 3.0.3 on 2020-03-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200305_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[(None, '(Aniqmas)'), ('BT', 'Budjet'), ('KT', 'Kantrakt')], default='(Aniqmas)', max_length=2, verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.IntegerField(choices=[(None, '(Aniqmas)'), (1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default='(Aniqmas)'),
        ),
    ]
