# Generated by Django 3.0.3 on 2020-03-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200305_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.IntegerField(choices=[(None, '(Aniqmas)'), (1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default='(Aniqmas)', verbose_name='Kursi'),
        ),
    ]
