# Generated by Django 3.0.3 on 2020-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200305_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, help_text='Fikr muloazalaringizni yozib qoldiring', null=True),
        ),
    ]
