# Generated by Django 3.0.3 on 2020-03-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_programminglanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='program_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.ProgrammingLanguage'),
        ),
    ]
